version: "3.8"

services:
  frontend:
    build: ./fe
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./be
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASS=secret
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
